language: go
sudo: true
services:
  - docker
go:
  - 1.11.x
jobs:
  include:
    - script: make test-container CMD="make all"
    - stage: Run Test Coverage
      script: make test-container CMD="make cover"
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make test-container CMD="make release"
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/bpfd-linux-amd64
          - cross/bpfd-linux-amd64.md5
          - cross/bpfd-linux-amd64.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "M1A4gQy2/ToCdg3IIrhpzdttRB6FsPq1ohhzDMmXk7hAYqiZJgKvoU80rmRfpIrjqJxFLkX3zgRGCpZC7ifSQTv9AWMqdMnKHL8ALIHKYoxaOFi302G6jKShTlxvT3EGARikW1NNkxOUvO89LR8HQEs6Ee0Ej4U+srxR7qAj9PmwbcQELm8VuGyT6OwJCgTounaIHQIuS195g/Og0M5P5s/V8d80X9TvWHwYPa5G7mbcIjKW20QHYDczY9S/LznVFVN+9hd9EiszWVDRRhYN7N+Msgd/etlAp1TkHZ4UsZKEpAIKHmks9Y/dg3WTIqgP/p9Dv6ddQ5tI4Zc9yAwaGyh5ToPAhJDZ+9UWFCkGOj/296rVCtykYa6pCYuLjdkHN9G2zDTQ1MgFuI+HDZVtIooGoCQIxepSeQYXX+l5mXurndqWf72JcRB2UFvN9336P4GjpUgpH6ml7r3bq00y2SNnBKEc6Nss4VWY1OLEGvYT6NJybmj0Wvqg0oAMvW6D8JnMg3nz4Kltzjvf39GkY8HHBpzCiav19kyDQxjKq6uR4F9eyfe5tficn3bLlwLX7RVUf7QZGVO/ZbidR2hw4ODZVcpXRsP0RC3hQVfi4EnR27fbDrRF0mqDmXMLOZjmrTwbz6d9mlNEpJwBqlXI1VrfXZIrPvDMJmHqDApR4YQ="
